### PR TITLE
Added TypeScript definitions for library

### PR DESCRIPTION
**Pull request by bdoss**

### CODE REVIEW

**Comment by toish** [comment]
Wow, thanks so much! Will merge this in and I'll add a note to the README about adding to this definitions file when contributing

One small nit-picky thing before that, the colour mode type for CSS_RGB + CSS_HSL might be better as CSSRGB and CSSHSL to better sync up with the colour mode labels used in conversions, keeps consistency with CIELAB as well.

**Comment by bdoss** [comment]
Funny you mention that about CSS_RGB and CSS_HSL prop naming, I was really on the fence about it and looked at it both ways trying to determine which was the better approach. :)

I'll update the pull request to CSSRGB and CSSHSL.

**Comment by toish** [comment]
Thanks so much again! :) Will make this lib way easier to use with typescript, controlling the mess of colour objects now

**Comment by bdoss** [comment]
Glad I could help! It's a great little library and very well documented! The definitions practically wrote themselves. :)

**Pull request merged**
