### PR TITLE
Convert function declarations to arrow functions

### PR DESCRIPTION
**Pull request by kale-io**

### CODE REVIEW

**Comment by toish** [comment]
Wow thank you! Not sure what's going on with hound CI here, will have to look into that!

I will be able to take a close look into this tomorrow and hopefully merge it in, thanks for catching these!

**Comment by iondrimba** [comment]
@toish maybe a missing ` .hound.yml` with an ` .eslintrc` config https://houndci.com/configuration#eslint

**Comment by kale-io** [comment]
Hey @toish any update on this? Do you need any help?

**Comment by kale-io** [comment]
@toish do you have any update on this? Thanks (:

**Comment by toish** [comment]
Hi @kale-io, sorry, work has me seriously drained and I haven't had the time to focus on this as much as I'd like to. My best assumption is that I just need to add `esversion: 6` to a hound.yml file. Would love some help, as I actually don't remember setting up HoundCI on this project, had some help from a friend a little while ago refactoring this project, and he may have added this project to a HoundCI account.

**Comment by TehShrike** [comment]
I'd never heard of HoundCI before this issue :-x

**Comment by kale-io** [comment]
Apparently, HoundCI uses JSHint by default:
https://houndci.com/configuration#javascript

So, in order to change the behavior, you need to specify the ES version in a `.jshintrc` file:

```
{
  "esversion": 6
}
```

Then, you need to reference this config file in your `.hound.yml` file:

```
jshint:
  config_file: .jshintrc
```

... that's what the docs say, at least.

**Comment by kale-io** [comment]
Opened a new pull request on the latest master. hound-ci is still hounding us there 😄. #37 should help.

**Pull request closed without merging**
