### PR TITLE
Refactor for v3

### PR DESCRIPTION
**Pull request by toish**
This is a major, breaking version bump, but all the following changes should make chromatism one of, if not the smallest colour libraries available (when using ES6 modules).

+ Added ES6 module
+ Added Uniform hue-shifting transforms (Using HSLuv)
+ Added More efficient conversion chain

- Removed Function Chaining
- Removed Illuminant + Transformation Matrix constants

### CODE REVIEW

**Comment by TehShrike** [comment]
:-D

Only major thing I can think of is that it would be cool to add a changelog.md file.  But, it would be better to publish this than to wait around for someone to add a writeup of all the changes.

**Comment by TehShrike** [comment]
All right, I'm to the point where I really want to save bytes by using the ESM version of this module!  Any reason not to merge and publish?

**Comment by toish** [comment]
Was looking for any one else to comment on it, think we're good to FINALLY do this anyway though!

**Comment by toish** [comment]
Currently at work, will publish when I'm free

**Pull request merged**
